- name: Setup .NET Core SDK
  uses: actions/setup-dotnet@v2.1.0
  with:
    dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 6.0 channel
- run: dotnet build ADB.NET.sln
